DROP INDEX IF EXISTS idx_flight_planeid;
DROP INDEX IF EXISTS idx_schedule_flightnumber;
DROP INDEX IF EXISTS idx_flightinstance_flightnumber;
DROP INDEX IF EXISTS idx_reservation_customerid;
DROP INDEX IF EXISTS idx_reservation_flightinstanceid;
DROP INDEX IF EXISTS idx_repair_planeid;
DROP INDEX IF EXISTS idx_repair_technicianid;
DROP INDEX IF EXISTS idx_maintenancerequest_planeid;
DROP INDEX IF EXISTS idx_maintenancerequest_pilotid;
DROP INDEX IF EXISTS idx_plane_lastrepairdate;
DROP INDEX IF EXISTS idx_flightinstance_flightdate;
DROP INDEX IF EXISTS idx_repair_repairdate;
DROP INDEX IF EXISTS idx_maintenancerequest_requestdate;
DROP INDEX IF EXISTS idx_customer_lastname;
DROP INDEX IF EXISTS idx_customer_phone;
DROP INDEX IF EXISTS idx_customer_zip;
DROP INDEX IF EXISTS idx_customer_name_combo;
DROP INDEX IF EXISTS idx_flight_departure_arrival;
DROP INDEX IF EXISTS idx_schedule_dayofweek;
DROP INDEX IF EXISTS idx_schedule_departuretime;
DROP INDEX IF EXISTS idx_reservation_status;
DROP INDEX IF EXISTS idx_flightinstance_departed;
DROP INDEX IF EXISTS idx_flightinstance_arrived;
DROP INDEX IF EXISTS idx_flightinstance_cost;
DROP INDEX IF EXISTS idx_flightinstance_date_flight;
DROP INDEX IF EXISTS idx_schedule_day_time;
DROP INDEX IF EXISTS idx_repair_plane_date;
DROP INDEX IF EXISTS idx_reservation_customer_status;
DROP INDEX IF EXISTS idx_repair_repaircode;
DROP INDEX IF EXISTS idx_maintenancerequest_repaircode;
DROP INDEX IF EXISTS idx_customer_password;
DROP INDEX IF EXISTS idx_technician_password;
DROP INDEX IF EXISTS idx_pilot_password;CREATE INDEX idx_flight_planeid ON Flight(PlaneID);

CREATE INDEX idx_schedule_flightnumber ON Schedule(FlightNumber);
CREATE INDEX idx_flightinstance_flightnumber ON FlightInstance(FlightNumber);
CREATE INDEX idx_reservation_customerid ON Reservation(CustomerID);
CREATE INDEX idx_reservation_flightinstanceid ON Reservation(FlightInstanceID);
CREATE INDEX idx_repair_planeid ON Repair(PlaneID);
CREATE INDEX idx_repair_technicianid ON Repair(TechnicianID);
CREATE INDEX idx_maintenancerequest_planeid ON MaintenanceRequest(PlaneID);
CREATE INDEX idx_maintenancerequest_pilotid ON MaintenanceRequest(PilotID);
CREATE INDEX idx_plane_lastrepairdate ON Plane(LastRepairDate);
CREATE INDEX idx_flightinstance_flightdate ON FlightInstance(FlightDate);
CREATE INDEX idx_repair_repairdate ON Repair(RepairDate);
CREATE INDEX idx_maintenancerequest_requestdate ON MaintenanceRequest(RequestDate);
CREATE INDEX idx_customer_lastname ON Customer(LastName);
CREATE INDEX idx_customer_phone ON Customer(Phone);
CREATE INDEX idx_customer_zip ON Customer(Zip);
CREATE INDEX idx_customer_name_combo ON Customer(LastName, FirstName);
CREATE INDEX idx_flight_departure_arrival ON Flight(DepartureCity, ArrivalCity);
CREATE INDEX idx_schedule_dayofweek ON Schedule(DayOfWeek);
CREATE INDEX idx_schedule_departuretime ON Schedule(DepartureTime);
CREATE INDEX idx_reservation_status ON Reservation(Status);
CREATE INDEX idx_flightinstance_departed ON FlightInstance(DepartedOnTime);
CREATE INDEX idx_flightinstance_arrived ON FlightInstance(ArrivedOnTime);
CREATE INDEX idx_flightinstance_cost ON FlightInstance(TicketCost);
CREATE INDEX idx_flightinstance_date_flight ON FlightInstance(FlightDate, FlightNumber);
CREATE INDEX idx_schedule_day_time ON Schedule(DayOfWeek, DepartureTime);
CREATE INDEX idx_repair_plane_date ON Repair(PlaneID, RepairDate);
CREATE INDEX idx_reservation_customer_status ON Reservation(CustomerID, Status);
CREATE INDEX idx_repair_repaircode ON Repair(RepairCode);
CREATE INDEX idx_maintenancerequest_repaircode ON MaintenanceRequest(RepairCode);
CREATE INDEX idx_customer_password ON Customer(Password);
CREATE INDEX idx_technician_password ON Technician(Password);
CREATE INDEX idx_pilot_password ON Pilot(Password);
